//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalogueWcfService.ServiceDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalogReading
    {
        public int UnitRequestID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string GroupName { get; set; }
        public string CustTypeID { get; set; }
        public string CustTypeName { get; set; }
        public Nullable<short> DeviceNo { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string Serial { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<int> AuxAnalogue { get; set; }
        public Nullable<int> DeviceLevel { get; set; }
        public Nullable<int> UsableLevel { get; set; }
        public Nullable<int> MeasuredLevel { get; set; }
        public Nullable<int> RecordType { get; set; }
        public Nullable<int> ErrorCondition { get; set; }
        public Nullable<int> ErrorConditionLink { get; set; }
        public string ErrorText { get; set; }
        public Nullable<double> AvgUsage { get; set; }
        public Nullable<double> DaysToEmpty { get; set; }
        public string AccountNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string HPhone { get; set; }
        public string WPhone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> DeviceSize { get; set; }
        public Nullable<int> DeviceSizeTotal { get; set; }
        public Nullable<int> DeviceCount { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> SubstanceID { get; set; }
        public string SubstanceName { get; set; }
    }
}
